name: SonarQube

on:
  push:
    branches: [next, main]
    paths:
      - 'soapui-installer/**'
      - 'soapui/**'                 # nécessaire si la dépendance change
      - '.github/workflows/**'
  pull_request:
    branches: [next, main]
    paths:
      - 'soapui-installer/**'
      - 'soapui/**'
      - '.github/workflows/**'

jobs:
  build-and-analyze:
    name: Build and analyze (Maven + Sonar)
    runs-on: ubuntu-latest
    # 👇 Ce bloc fait en sorte que le job ne se déclenche que si des fichiers dans soapui-installer changent
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
 
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
 
      - name: Build and analyze (Maven + Sonar)
        env:
          GITHUB_TOKEN:   ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN:    ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        run: |
          cd soapui-installer
          mvn -B -DskipTests -DskipITs -Dgpg.skip verify \
            org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
            -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
            -Dsonar.projectKey=Soapui \
            -Dsonar.projectName=Soapui
